### ISSUE TITLE
Add ability to sort projects by comment volume on a given day

### ISSUE THREAD

**Issue by PTPells** [MatmaRex/dtcheck#5]
This issue is about introducing the ability to sort the projects within dtcheck by the total number of comments posted to said project using the Reply Tool on a given day.

### Use case
Over the past ~2 weeks (from 6-Sep to 24-Aug), the total number of comments posted has varied quite a bit. On 5-Sep, people posted 308 total comments with the Reply Tool. On 31-August, people posted 1,533 total comments with the Reply Tool.

To understand what _could_ be contributing to a particularly low or high number of comments on a given day, I'd like to be look at individual projects and see how the current day's comment count compared from the previous day(s). Being able to sort project by comment would (I think?) enable me to identify changes in behavior at particular projects by: A)  "moving" all of the projects where 0 Reply Tool comments were posted _and_ B) seeing the projects likely having the biggest impact on aggregate comment count totals at the top of the list.

**Comment by MatmaRex** [comment]
Done in d14defdf992bcb98622f7c8b45ad2338b228c352, dde93b120f15d63c1dda10a1c989c12c98935a57. Also, it is sorted by the monthly total by default now (instead of the basically random order it had previously).

It's kind of very slow right now, because of the particular (shoddy) way the whole thing is built. Maybe I'll redo it differently some time. For now, you'll probably just want to copy the whole table into a spreadsheet (I've redone how the table is shown, so that copying it shouldn't behave funny any more).
