### ISSUE TITLE
Might dtcheck be miscounting the number of comments being posted with the Reply Tool?

### ISSUE THREAD

**Issue by PTPells** [MatmaRex/dtcheck#6]
This issue about investigating whether dtcheck might be miscounting the number of comments being posted with the Reply Tool.

### Issue
1. Visit: [fr:Special:RecentChanges](https://fr.wikipedia.org/w/index.php?hidebots=1&hidecategorization=1&hideWikibase=1&tagfilter=discussiontools-reply&limit=500&days=1&title=Sp%C3%A9cial:Modifications_r%C3%A9centes&urlversion=2)
2. Set Active filters to `#DiscussionTools (Reply)`
3.  Limit the search results to `500 changes, 1 day`
4. For `10 September 2021`, count a total of 54 edits that have been made with the `Tags: Reply` attached 
5. Visit https://dtcheck.toolforge.org/dtstats.html
6. View the column titled `2021-09-10`

**Actual**
7. ❗️Notice dtcheck says 18 edits have been posted with the Reply Tool at `fr.wikipedia.org`

**Expected**
8. ✅Notice dtcheck says 54 edits [i] have been posted with the Reply Tool at `fr.wikipedia.org`

---
i. Or something _like_ 54 edits; considering I assume there might be slight variation between the counts of the two tools.

**Comment by MatmaRex** [comment]
Indeed data is missing. The dtcheck database for that day only has edits made until around 10:00 UTC.

The problem seems to have started on 2021-08-18! On that day, only data until around 23:00 UTC is present. Older data seems complete.

Latest timestamp in dtcheck database for each day this month:
```
  "2021-08-12": "23:59:55Z",
  "2021-08-13": "23:58:40Z",
  "2021-08-14": "23:55:03Z",
  "2021-08-15": "23:58:34Z",
  "2021-08-16": "23:58:58Z",
  "2021-08-17": "23:56:24Z",
  "2021-08-18": "23:02:00Z",
  "2021-08-19": "23:00:25Z",
  "2021-08-20": "22:54:51Z",
  "2021-08-21": "23:00:31Z",
  "2021-08-22": "22:57:58Z",
  "2021-08-23": "22:01:52Z",
  "2021-08-24": "22:57:08Z",
  "2021-08-25": "21:59:18Z",
  "2021-08-26": "23:00:21Z",
  "2021-08-27": "22:57:37Z",
  "2021-08-28": "22:59:36Z",
  "2021-08-29": "22:58:19Z",
  "2021-08-30": "12:58:17Z",
  "2021-08-31": "22:02:37Z",
  "2021-09-01": "17:02:56Z",
  "2021-09-02": "12:00:39Z",
  "2021-09-03": "22:01:53Z",
  "2021-09-04": "11:59:53Z",
  "2021-09-05": "07:59:39Z",
  "2021-09-06": "05:58:37Z",
  "2021-09-07": "13:01:35Z",
  "2021-09-08": "12:00:54Z",
  "2021-09-09": "10:01:44Z",
  "2021-09-10": "10:01:37Z",
  "2021-09-11": "10:00:02Z",
  "2021-09-12": "05:01:09Z"
```
(generated using: `jq '[ .sites[].revisions[].timestamp | split("T") ] | group_by(.[0]) | [ .[] | {(.[0][0]): ([ .[
][1] ] | max) } ] | add'`)

**Comment by MatmaRex** [comment]
It looks like the jobs have been exceeding memory usage limits. The default limits are quite low (it looks like 512 MB, according to https://wikitech.wikimedia.org/wiki/Help:Toolforge/Kubernetes#Quotas_and_Resources, if that's the correct documentation page), and my scripts are also very inefficient, holding all the data in memory instead of using some real database.

I can probably increase the limits, just have to read the docs and figure out how. I'll do it tomorrow.

**Comment by PTPells** [comment]
> Indeed data is missing. The dtcheck database for that day only has edits made until around 10:00 UTC.

Woosh, this is relieving.

> It looks like the jobs have been exceeding memory usage limits. The default limits are quite low (it looks like 512 MB, according to https://wikitech.wikimedia.org/wiki/Help:Toolforge/Kubernetes#Quotas_and_Resources, if that's the correct documentation page)...

Huh, okay. 

> I can probably increase the limits, just have to read the docs and figure out how. I'll do it tomorrow.

Sounds good. Here's a task in Phabricator so the team has greater visibility of this issue: https://phabricator.wikimedia.org/T290835.

**Comment by MatmaRex** [comment]
Done in 80f83d2ab28819928741e17d230ab956c26cbcc2. I've also manually ran the scripts to update older data (it took 83 minutes, I started it earlier today and only remembered to check now).

I also saved the main page of dtcheck before and after the fix, for comparison. GitHub won't let me upload the HTML files (I'll put them on Phab), but here are screenshots:

before | ![old](https://user-images.githubusercontent.com/160413/133172276-b6022a7d-7de1-4620-b5a5-0d5c00f3f4da.png)
------------ | -------------
after | ![new](https://user-images.githubusercontent.com/160413/133172278-d124cf2b-9ae0-423d-92db-c4196e8cfc65.png)
